// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectBackend.DataContext;

namespace ProjectBackend.Migrations
{
    [DbContext(typeof(BeerContext))]
    partial class BeerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ProjectBackend.Models.Beer", b =>
                {
                    b.Property<Guid>("BeerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BitternessId")
                        .HasColumnType("int");

                    b.Property<int>("BrewerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Percentage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeerId");

                    b.HasIndex("BitternessId");

                    b.HasIndex("BrewerId");

                    b.ToTable("Beer");

                    b.HasData(
                        new
                        {
                            BeerId = new Guid("a479f7b7-e969-4a5c-b4ff-eb09b934427e"),
                            BitternessId = 1,
                            BrewerId = 1,
                            Name = "Stella Artois",
                            Origin = "Leuven",
                            Percentage = "5.2"
                        },
                        new
                        {
                            BeerId = new Guid("6f92eca8-e714-4e40-9fe0-9598b2e82b93"),
                            BitternessId = 2,
                            BrewerId = 2,
                            Name = "Jupiler",
                            Origin = "Jupille-sur-Meuse",
                            Percentage = "5.2"
                        },
                        new
                        {
                            BeerId = new Guid("3c9c62b4-10c5-4fe2-b31e-efe4177d0ac1"),
                            BitternessId = 1,
                            BrewerId = 1,
                            Name = "Heineken",
                            Origin = "Amsterdam",
                            Percentage = "5"
                        });
                });

            modelBuilder.Entity("ProjectBackend.Models.Bitterness", b =>
                {
                    b.Property<int>("BitternessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AmountIBU")
                        .HasColumnType("int");

                    b.HasKey("BitternessId");

                    b.ToTable("Bitterness");

                    b.HasData(
                        new
                        {
                            BitternessId = 1,
                            AmountIBU = 25
                        },
                        new
                        {
                            BitternessId = 2,
                            AmountIBU = 20
                        });
                });

            modelBuilder.Entity("ProjectBackend.Models.Brewer", b =>
                {
                    b.Property<int>("BrewerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("HeadOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrewerId");

                    b.ToTable("Brewer");

                    b.HasData(
                        new
                        {
                            BrewerId = 1,
                            HeadOffice = "Leuven",
                            Name = "AB InBev"
                        },
                        new
                        {
                            BrewerId = 2,
                            HeadOffice = "Luik",
                            Name = "Piedboeuf"
                        });
                });

            modelBuilder.Entity("ProjectBackend.Models.Beer", b =>
                {
                    b.HasOne("ProjectBackend.Models.Bitterness", "Bitterness")
                        .WithMany("Beer")
                        .HasForeignKey("BitternessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBackend.Models.Brewer", "Brewer")
                        .WithMany("Beer")
                        .HasForeignKey("BrewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bitterness");

                    b.Navigation("Brewer");
                });

            modelBuilder.Entity("ProjectBackend.Models.Bitterness", b =>
                {
                    b.Navigation("Beer");
                });

            modelBuilder.Entity("ProjectBackend.Models.Brewer", b =>
                {
                    b.Navigation("Beer");
                });
#pragma warning restore 612, 618
        }
    }
}
